---
title: "GNP Models"
author: "Katie Grabowski"
date: "7/28/2020"
output: html_document
editor_options: 
  chunk_output_type: console
---
Here we go!
#install packages 
```{r}
library("unmarked") #install.packages("unmarked")
library(camtrapR) #install.packages("camtrapR")
library(tidyverse)
library(dplyr)
```

#use unmarkedFrameOccuMulti to create the data object
```{r}
# load in detection histories
genet_dh <-read_csv("data/gorongosa-cameras/genet.csv", col_names = FALSE) %>% as.matrix()

civet_dh <-read_csv("data/gorongosa-cameras/civet.csv", col_names = FALSE) %>% as.matrix()

honeybadger_dh <-read_csv("data/gorongosa-cameras/honey_badger.csv", col_names = FALSE) %>% as.matrix()

marshmongoose_dh <-read_csv("data/gorongosa-cameras/marsh_mongoose.csv", col_names = FALSE) %>% as.matrix()

#I know I could have done this in the function, but separating it made more sense for me
y <- list(genet_dh, civet_dh, honeybadger_dh, marshmongoose_dh)
names(y) <- c('genet','civet','honey badger', 'marsh mongoose')

#load occupancy covariates
#leaving the column names in for now
occ_covs <- read_csv("data/gorongosa-cameras/GNP covariates.csv", col_names = TRUE) %>% as.data.frame()

data <- unmarkedFrameOccuMulti(y = y, siteCovs = occ_covs)

#look at data
summary(data)
plot(data)

# Look at f parameter design matrix
data@fDesign
data@ylist
```
my f equation order: 
f1: genet
f2: civet
f3: honey badger
f4: marsh mongoose
f5: genet: civet
f6: genet: honey badger
f7: genet: marsh mongoose
f8: civet: honey badger
f9: civet: marsh mongoose
f10: honey badger: marsh mongoose

#run occuMulti
```{r}
# Formulas for state and detection processes

# Length should match number/order of columns in fDesign
occFormulas <- c('~urema_dist','~tree_hansen','~termite.large.count.100m','~lion_camera','~1','~1','~1','~1','~1','~1', '0', '0', '0', '0', '0')

#Length should match number/order of species in data@ylist (genet, civet, honey badger, marsh mongoose)
detFormulas <- c('~detect.obscured+cover.ground', '~detect.obscured+cover.ground', '~detect.obscured+cover.ground', '~detect.obscured+cover.ground')

fit <- occuMulti(detFormulas, stateformulas = occFormulas, data)
```

# explore model output
```{r}
#Look at output
fit

occ <- summary(fit[1]) 

write_csv(occ, "data/gorongosa-cameras/fit_occ.csv", col_names = T)

#plot(fit)

# occupancy only
fit@estimates[1]

# detection only
fit@estimates[2]

unclass(fit) 
attr(fit, "estimates") 
as.data.frame(coef(fit))

#predict method
lapply(predict(fit,'state'),head)
lapply(predict(fit,'det'),head)

#marginal occupancy
head(predict(fit,'state',species=2))
head(predict(fit,'state',species='genet')) # why is this all 1 / 0 / 0?
head(predict(fit,'det',species='civet')) # why are all of these the same?
```

